### ISSUE TITLE
Checklist: Weapon FX Pass

### ISSUE THREAD

**Issue by IrateRedKite** [TheStarport/freelancer-bmod#10]
We want to do a pass on all the rejigged 'vanilla' weapons we're using. This issue is here to track progress and discuss approaches/progress.

- [x] beagle_gd_bh_gun01
- [x] beagle_gd_bh_turret01
- [x] beagle_gd_bh_gun02
- [x] beagle_gd_bh_turret02
- [x] beagle_gd_bh_gun03
- [x] beagle_gd_bh_turret03
- [x] beagle_gd_civ_grp_turret02
- [x] beagle_gd_civ_grp_gun01
- [x] beagle_gd_civ_grp_turret01
- [x] beagle_gd_civ_grp_gun02
- [x] beagle_fc_j_grp_gun01
- [x] beagle_fc_j_grp_turret01
- [x] beagle_fc_lh_grp_turret01
- [x] beagle_fc_lh_grp_gun01
- [x] beagle_li_n_grp_gun01
- [x] beagle_li_n_grp_gun02
- [x] beagle_li_n_grp_gun03
- [x] beagle_li_n_grp_turret01
- [x] beagle_li_n_grp_turret02
- [x] beagle_li_n_grp_turret03
- [x] beagle_fc_lr_gr_gun01
- [x] beagle_fc_lr_grp_turret01
- [x] beagle_fc_lr_gr_gun02
- [x] beagle_fc_lr_grp_turret02
- [x] beagle_fc_lr_gr_gun03
- [x] beagle_fc_lr_grp_turret03
- [x] beagle_fc_ou_grp_gun01
- [x] beagle_fc_ou_grp_turret01
- [x] beagle_fc_ou_grp_gun02
- [x] beagle_fc_ou_grp_turret02
- [x] beagle_fc_ou_grp_gun03
- [x] beagle_fc_ou_grp_turret03
- [x] beagle_fc_x_grp_gun01
- [x] beagle_fc_x_grp_gun02
