### ISSUE TITLE
Milo's Big 0.1 VFX Tracking Issue

### ISSUE THREAD

**Issue by IrateRedKite** [TheStarport/freelancer-bmod#94]
Using this to keep track of VFX that need doing. Core issue will be updated as new gear gets finalized for this build.

- [x] Repair Mine Explosion
- [x] Repair Mine Pulse
- [x] PPC Projectile
- [x] PPC Muzzle Flash + Reload
- [x] PPC Impact
- [x] Rocket Pod Projectile
- [x] Rocket Pod Impact
- [x] SRM Pass
- [x] LRM Pass
- [x] Solo LRM Launcher Muzzle Flash
- [x] Solo SRM Launcher Muzzle Flash
- [ ] Fleet ER Laser
- [ ] Torpedoes
- [x] Unguided Bomb Trail
- [x] Unguided Bomb Light
- [x] Unguided Bomb Explosion
- [x] Junker Gun
- [x] Cruise Disruptor
- [ ] CSV Engine FX
